name: release
on:
  push:
    tags:
      - "*"

jobs:
  changelog:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
  release:
    needs: changelog
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cross: false
            file-ext: ""
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false
            file-ext: .exe
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            cross: true
            file-ext: .exe
          - target: x86_64-apple-darwin
            os: macos-latest
            cross: false
            file-ext: ""
          - target: x86_64-linux-android
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            cross: true
            file-ext: ""
          - target: aarch64-linux-android
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: aarch64-apple-ios
            os: macos-latest
            cross: true
            file-ext: ""
          - target: arm-unknown-linux-gnueabihf
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: armv7-linux-androideabi
            os: ubuntu-latest
            cross: true
            file-ext: ""
          
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Compress binaries
        continue-on-error: true
        uses: svenstaro/upx-action@v2
        with:
          file: target/${{ matrix.target }}/release/trr${{ matrix.file-ext }}
          args: -q --best --lzma
          strip: ${{ (!startsWith(matrix.target, 'aarch') && !startsWith(matrix.target, 'arm')) || matrix.target == 'aarch64-apple-ios' }}
      - name: pack
        run: |
          mkdir -p release-${{ matrix.target }}
          cd release-${{ matrix.target }}
          tar -C ../target/${{ matrix.target }}/release -zcf trr-${{ matrix.target }}.tar.gz trr${{ matrix.file-ext }}
          openssl dgst -sha256 -r trr-${{ matrix.target }}.tar.gz > trr-${{ matrix.target }}.sha256
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: release-${{ matrix.target }}/*